name: Exploit the world
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build-and-exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "17"
      - name: Build
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          cd slim-demo/
          mkdir -p ~/.m2
          cp .mvn/settings.xml ~/.m2/settings.xml
          mvn clean package
      - name: Run Exploited JAR
        run: |
          cd slim-demo
          java -jar target/poc-0.0.1-SNAPSHOT-shaded.jar src/test/AnterosDBCPConfig.json
      - name: Check Exploit Success or Failure
        run: |
          cd slim-demo
          cat ./CVE.txt
