name: Exploit the world
on:
  workflow_dispatch:
  pull_request:
    branches: [main]    

jobs:
  build-and-exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Build  
        run: |
          mvn clean package
      - name: Run Exploited JAR
        run: java -jar target/poc-0.0.1-SNAPSHOT-shaded.jar src/test/AnterosDBCPConfig.json
      - name: Check Exploit Success or Failure
        run: cat ./CVE.txt